# Generated by Django 4.1.7 on 2023-03-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staffdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinese',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coolers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dessert',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotdrinks',
            name='image',
        ),
        migrations.RemoveField(
            model_name='milkshake',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mojito',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pavbhaji',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.RemoveField(
            model_name='punjabi',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sandwitch',
            name='image',
        ),
        migrations.RemoveField(
            model_name='southindian',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
