# Generated by Django 4.1.7 on 2023-03-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_burger_name_alter_chinese_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coolers',
        ),
    ]
