# Generated by Django 4.1.7 on 2023-04-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_delete_coolers"),
    ]

    operations = [
        migrations.CreateModel(
            name="checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.JSONField()),
            ],
        ),
    ]
